version: "2.1"
services:
  postgres:
    image: clkao/postgres-plv8
    container_name: postgres
    hostname: postgres
    environment:
      - variables.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - guesswork_network
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - guesswork_network
    healthcheck:
      test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
      interval: 10s
      retries: 5
  web:
    build:
      dockerfile: src/Web/Dockerfile
      context: .
    container_name: web
    ports:
      - "80:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - guesswork_network
networks:
  guesswork_network:
    driver: bridge
volumes:
  db-data: